name: pngpetite
version: "0.2.2"
summary: Make PNG files as petite as possible
description: |
  A script to reduce the size of PNG images significantly.
  The code is based on Crush by Christopher Simpkins and
  has been adapted to Linux by refactoring it. As the code
  base shows significant differences the name has also been
  changed.

grade: devel
confinement: devmode
base: core18

parts:
  pngpetite:
    source: https://github.com/uroesch/pngpetite.git
    plugin: dump
    source-type: git
    source-tag: v0.2.2
    stage-packages:
      - libreadline7
      - bc
      - file
      - pngquant
      - zopfli
    build-packages:
      - git
apps:
  pngpetite:
    command: |
      bin/pngpetite
